### PR TITLE
Function to extract average color from blurhash

### PR DESCRIPTION
**Pull request by Tunous**
Function which extracts average color from a blur hash and returns it as SwiftUI.Color.

### CODE REVIEW

**Comment by iankoex** [comment]
I have run the demo app. What do you hope to achieve by getting the average Color?

**Comment by Tunous** [comment]
I want to add some extra styling to user interface that is connected to blurhash images. For example here I'm using it to colorize background under text near video. I have blurhash from the server so I thought it would be nice to use it for coloring too.

image

**Comment by iankoex** [comment]
Okay that's fine. 
PS: Your app looks amazing.

**Comment by iankoex** [comment]
Available now as 1.0.3. Thanks for your contribution.

**Comment by Tunous** [comment]
Thanks!

**Pull request merged**
